services:
  postgres:
    container_name: agrupamento_relacionamentos
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5434:5432"